SETTINGS := "D:\Dev\AHK\MacroTool\Settings.ini"

IniReader(key, value) {
  Global SETTINGS
  IniRead, OUTPUT, %SETTINGS%, %key%, %value%
  Return, %OUTPUT%
}

IniSaver() {
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk1"
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk2"
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk3"
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk4"
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk5"
  IniWrite, OUTPUT, %SETTINGS%, "Hotkeys", "hk6"

  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm1"
  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm2"
  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm3"
  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm4"
  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm5"
  IniWrite, OUTPUT, %SETTINGS%, "Bookmarks", "bm6"

  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app1"
  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app2"
  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app3"
  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app4"
  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app5"
  IniWrite, OUTPUT, %SETTINGS%, "Apps", "app6"

  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder1"
  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder2"
  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder3"
  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder4"
  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder5"
  IniWrite, OUTPUT, %SETTINGS%, "Folders", "folder6"

}

BM1 := IniReader("Bookmarks", "bm1")
BM2 := IniReader("Bookmarks", "bm2")
BM3 := IniReader("Bookmarks", "bm3")
BM4 := IniReader("Bookmarks", "bm4")
BM5 := IniReader("Bookmarks", "bm5")
BM6 := IniReader("Bookmarks", "bm6")

APP1 := IniReader("Apps", "app1")
APP2 := IniReader("Apps", "app2")
APP3 := IniReader("Apps", "app3")
APP4 := IniReader("Apps", "app4")
APP5 := IniReader("Apps", "app5")
APP6 := IniReader("Apps", "app6")

FOLDER1 := IniReader("Folders", "folder1")
FOLDER2 := IniReader("Folders", "folder2")
FOLDER3 := IniReader("Folders", "folder3")
FOLDER4 := IniReader("Folders", "folder4")
FOLDER5 := IniReader("Folders", "folder5")
FOLDER6 := IniReader("Folders", "folder6")


; Generated by AutoGUI 2.2.5a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, StatusBar,, Status Bar
Gui Add, Tab3, x416 y256 w0 h0, Tab 1|Tab 2
Gui Add, Tab3, x8 y8 w578 h538, BookMarks|Apps|Folders
Gui Tab, 1, 2
Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
Gui Add, Text, x32 y112 w32 h21 +0x200 Center, 3
Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
Gui Add, Edit, x72 y48 w411 h24 vmyEditBM1
Gui Add, Edit, x72 y80 w411 h24 vmyEditBM2
Gui Add, Edit, x72 y112 w411 h24 vmyEditBM3
Gui Add, Edit, x72 y144 w411 h24 vmyEditBM4
Gui Add, Edit, x72 y176 w411 h24 vmyEditBM5
Gui Add, Edit, x72 y208 w411 h24 vmyEditBM6

Gui Tab, 2, 2
Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
Gui Add, Edit, x72 y48 w411 h24 vmyEditAPP1
Gui Add, Edit, x72 y80 w411 h24 vmyEditAPP2
Gui Add, Edit, x72 y112 w411 h24 vmyEditAPP3
Gui Add, Edit, x72 y144 w411 h24 vmyEditAPP4
Gui Add, Edit, x72 y176 w411 h24 vmyEditAPP5
Gui Add, Edit, x72 y208 w411 h24 vmyEditAPP6

Gui Tab, 3, 2
Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
Gui Add, Edit, x72 y48 w411 h24 vmyEditFOLDER1
Gui Add, Edit, x72 y80 w411 h24 vmyEditFOLDER2
Gui Add, Edit, x72 y112 w411 h24 vmyEditFOLDER3
Gui Add, Edit, x72 y144 w411 h24 vmyEditFOLDER4
Gui Add, Edit, x72 y176 w411 h24 vmyEditFOLDER5
Gui Add, Edit, x72 y208 w411 h24 vmyEditFOLDER6

Gui, Add, Button, x10 y10 h50 w50 gDoSomething, Button That Does Something

saveSettings:
   iniSaver()
return

GuiControl,, myEditBM1, %BM1%
GuiControl,, myEditBM2, %BM2%
GuiControl,, myEditBM3, %BM3%
GuiControl,, myEditBM4, %BM4%
GuiControl,, myEditBM5, %BM5%
GuiControl,, myEditBM6, %BM6%

GuiControl,, myEditAPP1, %APP1%
GuiControl,, myEditAPP2, %APP2%
GuiControl,, myEditAPP3, %APP3%
GuiControl,, myEditAPP4, %APP4%
GuiControl,, myEditAPP5, %APP5%
GuiControl,, myEditAPP6, %APP6%

GuiControl,, myEditFOLDER1, %FOLDER1%
GuiControl,, myEditFOLDER2, %FOLDER2%
GuiControl,, myEditFOLDER3, %FOLDER3%
GuiControl,, myEditFOLDER4, %FOLDER4%
GuiControl,, myEditFOLDER5, %FOLDER5%
GuiControl,, myEditFOLDER6, %FOLDER6%


Gui Show, w550 h576, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line



