; --> Global

  FILENAME := "/Settings.ini"
  SETTINGS = %A_WorkingDir%%FILENAME%

  IniReader(key, value) {
    Global SETTINGS
    IniRead, OUTPUT, %SETTINGS%, %key%, %value%
    Return, %OUTPUT%
  }

  IniSaver(input, key, value) {
    Global SETTINGS
    IniWrite, %input%, %SETTINGS%, %key%, %value%
    Return, %OUTPUT%
  }

  ; --> Read in Settings from INI

    HK1 := IniReader("Hotkeys", "1")
    HK2 := IniReader("Hotkeys", "2")
    HK3 := IniReader("Hotkeys", "3")
    HK4 := IniReader("Hotkeys", "4")
    HK5 := IniReader("Hotkeys", "5")
    HK6 := IniReader("Hotkeys", "6")

    BM1 := IniReader("Bookmarks", "1")
    BM2 := IniReader("Bookmarks", "2")
    BM3 := IniReader("Bookmarks", "3")
    BM4 := IniReader("Bookmarks", "4")
    BM5 := IniReader("Bookmarks", "5")
    BM6 := IniReader("Bookmarks", "6")

    APP1 := IniReader("Apps", "1")
    APP2 := IniReader("Apps", "2")
    APP3 := IniReader("Apps", "3")
    APP4 := IniReader("Apps", "4")
    APP5 := IniReader("Apps", "5")
    APP6 := IniReader("Apps", "6")

    FOLDER1 := IniReader("Folders", "1")
    FOLDER2 := IniReader("Folders", "2")
    FOLDER3 := IniReader("Folders", "3")
    FOLDER4 := IniReader("Folders", "4")
    FOLDER5 := IniReader("Folders", "5")
    FOLDER6 := IniReader("Folders", "6")

    M_BM_1 := IniReader("BMMenu", "1")
    M_BM_2 := IniReader("BMMenu", "2")
    M_BM_3 := IniReader("BMMenu", "3")
    M_BM_4 := IniReader("BMMenu", "4")
    M_BM_5 := IniReader("BMMenu", "5")
    M_BM_6 := IniReader("BMMenu", "6")

    M_APP_1 := IniReader("APPMenu", "1")
    M_APP_2 := IniReader("APPMenu", "2")
    M_APP_3 := IniReader("APPMenu", "3")
    M_APP_4 := IniReader("APPMenu", "4")
    M_APP_5 := IniReader("APPMenu", "5")
    M_APP_6 := IniReader("APPMenu", "6")

    M_FOLDER_1 := IniReader("FOLDERMenu", "1")
    M_FOLDER_2 := IniReader("FOLDERMenu", "2")
    M_FOLDER_3 := IniReader("FOLDERMenu", "3")
    M_FOLDER_4 := IniReader("FOLDERMenu", "4")
    M_FOLDER_5 := IniReader("FOLDERMenu", "5")
    M_FOLDER_6 := IniReader("FOLDERMenu", "6")

  ; --|

;--|

; --> GUI

  ; Generated by AutoGUI 2.2.5a
  #NoEnv
  #SingleInstance Force
  SetWorkingDir %A_ScriptDir%

  Gui Add, StatusBar,, Status Bar
  Gui Add, Tab3, x416 y256 w0 h0, Tab 1|Tab 2
  Gui Add, Tab3, x8 y8 w536 h350, Hotkeys|BookMarks|Apps|Folders|Menus
  Gui Tab, 1, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w32 h21 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditHK1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditHK2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditHK3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditHK4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditHK5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditHK6
  Gui Add, Button, x32 y250 h30 w100 gsaveHotkeys, Save Hotkeys

  Gui Tab, 2, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w32 h21 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditBM1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditBM2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditBM3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditBM4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditBM5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditBM6
  Gui Add, Button, x32 y250 h30 w100 gsaveBookmarks, Save Bookmarks

  Gui Tab, 3, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditAPP1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditAPP2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditAPP3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditAPP4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditAPP5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditAPP6
  Gui Add, Button, x32 y250 h30 w100 gsaveApps, Save Apps

  Gui Tab, 4, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditFOLDER1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditFOLDER2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditFOLDER3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditFOLDER4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditFOLDER5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditFOLDER6
  Gui Add, Button, x32 y250 h30 w100 gsaveFolders, Save Folders

  Gui Tab, 5, 2

  GUI, FONT, S16
  Gui Add, Text, x60 y48 w105 h23 +0x200 Center, Bookmarks
  GUI, FONT, S10
  Gui Add, Text, x32 y88 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y120 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y152 w33 h23 +0x200 Center, 3
  Gui Add, Text, x32 y184 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y216 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y248 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y88 w105 h24 vmyEditBMMENU1
  Gui Add, Edit, x72 y120 w105 h24 vmyEditBMMENU2
  Gui Add, Edit, x72 y152 w105 h24 vmyEditBMMENU3
  Gui Add, Edit, x72 y184 w105 h24 vmyEditBMMENU4
  Gui Add, Edit, x72 y216 w105 h24 vmyEditBMMENU5
  Gui Add, Edit, x72 y248 w105 h24 vmyEditBMMENU6

  GUI, FONT, S16
  Gui Add, Text, x210 y48 w105 h23 +0x200 Center, Apps
  GUI, FONT, S10
  Gui Add, Text, x190 y88 w33 h23 +0x200 Center, 1
  Gui Add, Text, x190 y120 w33 h23 +0x200 Center, 2
  Gui Add, Text, x190 y152 w33 h23 +0x200 Center, 3
  Gui Add, Text, x190 y184 w33 h23 +0x200 Center, 4
  Gui Add, Text, x190 y216 w33 h23 +0x200 Center, 5
  Gui Add, Text, x190 y248 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x230 y88 w105 h24 vmyEditAPPMENU1
  Gui Add, Edit, x230 y120 w105 h24 vmyEditAPPMENU2
  Gui Add, Edit, x230 y152 w105 h24 vmyEditAPPMENU3
  Gui Add, Edit, x230 y184 w105 h24 vmyEditAPPMENU4
  Gui Add, Edit, x230 y216 w105 h24 vmyEditAPPMENU5
  Gui Add, Edit, x230 y248 w105 h24 vmyEditAPPMENU6

  GUI, FONT, S16
  Gui Add, Text, x380 y48 w105 h23 +0x200 Center, Folders
  GUI, FONT, S10
  Gui Add, Text, x350 y88 w33 h23 +0x200 Center, 1
  Gui Add, Text, x350 y120 w33 h23 +0x200 Center, 2
  Gui Add, Text, x350 y152 w33 h23 +0x200 Center, 3
  Gui Add, Text, x350 y184 w33 h23 +0x200 Center, 4
  Gui Add, Text, x350 y216 w33 h23 +0x200 Center, 5
  Gui Add, Text, x350 y248 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x390 y88 w105 h24 vmyEditFOLDERMENU1
  Gui Add, Edit, x390 y120 w105 h24 vmyEditFOLDERMENU2
  Gui Add, Edit, x390 y152 w105 h24 vmyEditFOLDERMENU3
  Gui Add, Edit, x390 y184 w105 h24 vmyEditFOLDERMENU4
  Gui Add, Edit, x390 y216 w105 h24 vmyEditFOLDERMENU5
  Gui Add, Edit, x390 y248 w105 h24 vmyEditFOLDERMENU6

  Gui Add, Button, x32 y290 h30 w100 gsaveMenus, Save Menus!

  GuiControl,, myEditHK1, %HK1%
  GuiControl,, myEditHK2, %HK2%
  GuiControl,, myEditHK3, %HK3%
  GuiControl,, myEditHK4, %HK4%
  GuiControl,, myEditHK5, %HK5%
  GuiControl,, myEditHK6, %HK6%

  GuiControl,, myEditBM1, %BM1%
  GuiControl,, myEditBM2, %BM2%
  GuiControl,, myEditBM3, %BM3%
  GuiControl,, myEditBM4, %BM4%
  GuiControl,, myEditBM5, %BM5%
  GuiControl,, myEditBM6, %BM6%

  GuiControl,, myEditAPP1, %APP1%
  GuiControl,, myEditAPP2, %APP2%
  GuiControl,, myEditAPP3, %APP3%
  GuiControl,, myEditAPP4, %APP4%
  GuiControl,, myEditAPP5, %APP5%
  GuiControl,, myEditAPP6, %APP6%

  GuiControl,, myEditFOLDER1, %FOLDER1%
  GuiControl,, myEditFOLDER2, %FOLDER2%
  GuiControl,, myEditFOLDER3, %FOLDER3%
  GuiControl,, myEditFOLDER4, %FOLDER4%
  GuiControl,, myEditFOLDER5, %FOLDER5%
  GuiControl,, myEditFOLDER6, %FOLDER6%

  GuiControl,, myEditBMMENU1, %M_BM_1%
  GuiControl,, myEditBMMENU2, %M_BM_2%
  GuiControl,, myEditBMMENU3, %M_BM_3%
  GuiControl,, myEditBMMENU4, %M_BM_4%
  GuiControl,, myEditBMMENU5, %M_BM_5%
  GuiControl,, myEditBMMENU6, %M_BM_6%

  GuiControl,, myEditAPPMENU1, %M_APP_1%
  GuiControl,, myEditAPPMENU2, %M_APP_2%
  GuiControl,, myEditAPPMENU3, %M_APP_3%
  GuiControl,, myEditAPPMENU4, %M_APP_4%
  GuiControl,, myEditAPPMENU5, %M_APP_5%
  GuiControl,, myEditAPPMENU6, %M_APP_6%

  GuiControl,, myEditFOLDERMENU1, %M_FOLDER_1%
  GuiControl,, myEditFOLDERMENU2, %M_FOLDER_2%
  GuiControl,, myEditFOLDERMENU3, %M_FOLDER_3%
  GuiControl,, myEditFOLDERMENU4, %M_FOLDER_4%
  GuiControl,, myEditFOLDERMENU5, %M_FOLDER_5%
  GuiControl,, myEditFOLDERMENU6, %M_FOLDER_6%


  Gui Show, w550 h400, Window
  Return

  GuiEscape:
  GuiClose:
      ExitApp

; --|

; --> Sub Routines
  saveHotkeys:
    guiControlGet, hk1Var,, myEditHK1
    guiControlGet, hk2Var,, myEditHK2
    guiControlGet, hk3Var,, myEditHK3
    guiControlGet, hk4Var,, myEditHK4
    guiControlGet, hk5Var,, myEditHK5
    guiControlGet, hk6Var,, myEditHK6
    IniSaver(hk1Var, "Hotkeys", "1")
    IniSaver(hk2Var, "Hotkeys", "2")
    IniSaver(hk3Var, "Hotkeys", "3")
    IniSaver(hk4Var, "Hotkeys", "4")
    IniSaver(hk5Var, "Hotkeys", "5")
    IniSaver(hk6Var, "Hotkeys", "6")

    MsgBox % "Hotkeys Saved!"

  Return

  saveBookmarks:
    guiControlGet, bm1Var,, myEditBM1
    guiControlGet, bm2Var,, myEditBM2
    guiControlGet, bm3Var,, myEditBM3
    guiControlGet, bm4Var,, myEditBM4
    guiControlGet, bm5Var,, myEditBM5
    guiControlGet, bm6Var,, myEditBM6
    IniSaver(bm1Var, "Bookmarks", "1")
    IniSaver(bm2Var, "Bookmarks", "2")
    IniSaver(bm3Var, "Bookmarks", "3")
    IniSaver(bm4Var, "Bookmarks", "4")
    IniSaver(bm5Var, "Bookmarks", "5")
    IniSaver(bm6Var, "Bookmarks", "6")

    MsgBox % "Bookmarks Saved!"
  Return

  saveApps:
    guiControlGet, app1Var,, myEditAPP1
    guiControlGet, app2Var,, myEditAPP2
    guiControlGet, app3Var,, myEditAPP3
    guiControlGet, app4Var,, myEditAPP4
    guiControlGet, app5Var,, myEditAPP5
    guiControlGet, app6Var,, myEditAPP6
    IniSaver(app1Var, "Apps", "1")
    IniSaver(app2Var, "Apps", "2")
    IniSaver(app3Var, "Apps", "3")
    IniSaver(app4Var, "Apps", "4")
    IniSaver(app5Var, "Apps", "5")
    IniSaver(app6Var, "Apps", "6")

    MsgBox % "Apps Saved!"

  Return

  saveFolders:
    guiControlGet, folder1Var,, myEditFOLDER1
    guiControlGet, folder2Var,, myEditFOLDER2
    guiControlGet, folder3Var,, myEditFOLDER3
    guiControlGet, folder4Var,, myEditFOLDER4
    guiControlGet, folder5Var,, myEditFOLDER5
    guiControlGet, folder6Var,, myEditFOLDER6
    IniSaver(folder1Var, "Folders", "1")
    IniSaver(folder2Var, "Folders", "2")
    IniSaver(folder3Var, "Folders", "3")
    IniSaver(folder4Var, "Folders", "4")
    IniSaver(folder5Var, "Folders", "5")
    IniSaver(folder6Var, "Folders", "6")

    MsgBox % "Folders Saved!"

  Return

  saveMenus:
    guiControlGet, BM_M_1Var,, myEditBMMENU1
    guiControlGet, BM_M_2Var,, myEditBMMENU2
    guiControlGet, BM_M_3Var,, myEditBMMENU3
    guiControlGet, BM_M_4Var,, myEditBMMENU4
    guiControlGet, BM_M_5Var,, myEditBMMENU5
    guiControlGet, BM_M_6Var,, myEditBMMENU6
    IniSaver(BM_M_1Var, "BMMenu", "1")
    IniSaver(BM_M_2Var, "BMMenu", "2")
    IniSaver(BM_M_3Var, "BMMenu", "3")
    IniSaver(BM_M_4Var, "BMMenu", "4")
    IniSaver(BM_M_5Var, "BMMenu", "5")
    IniSaver(BM_M_6Var, "BMMenu", "6")

    guiControlGet, APP_M_1Var,, myEditAPPMENU1
    guiControlGet, APP_M_2Var,, myEditAPPMENU2
    guiControlGet, APP_M_3Var,, myEditAPPMENU3
    guiControlGet, APP_M_4Var,, myEditAPPMENU4
    guiControlGet, APP_M_5Var,, myEditAPPMENU5
    guiControlGet, APP_M_6Var,, myEditAPPMENU6
    IniSaver(APP_M_1Var, "APPMenu", "1")
    IniSaver(APP_M_2Var, "APPMenu", "2")
    IniSaver(APP_M_3Var, "APPMenu", "3")
    IniSaver(APP_M_4Var, "APPMenu", "4")
    IniSaver(APP_M_5Var, "APPMenu", "5")
    IniSaver(APP_M_6Var, "APPMenu", "6")

    guiControlGet, FOLDER_M_1Var,, myEditFOLDERMENU1
    guiControlGet, FOLDER_M_2Var,, myEditFOLDERMENU2
    guiControlGet, FOLDER_M_3Var,, myEditFOLDERMENU3
    guiControlGet, FOLDER_M_4Var,, myEditFOLDERMENU4
    guiControlGet, FOLDER_M_5Var,, myEditFOLDERMENU5
    guiControlGet, FOLDER_M_6Var,, myEditFOLDERMENU6
    IniSaver(FOLDER_M_1Var, "FOLDERMenu", "1")
    IniSaver(FOLDER_M_2Var, "FOLDERMenu", "2")
    IniSaver(FOLDER_M_3Var, "FOLDERMenu", "3")
    IniSaver(FOLDER_M_4Var, "FOLDERMenu", "4")
    IniSaver(FOLDER_M_5Var, "FOLDERMenu", "5")
    IniSaver(FOLDER_M_6Var, "FOLDERMenu", "6")

    MsgBox % "Menus Saved!"
    Reload

  Return

;--|
