
; --> Global

  SETTINGS := "D:\Dev\AHK\MacroTool\Settings.ini"

  IniReader(key, value) {
    Global SETTINGS
    IniRead, OUTPUT, %SETTINGS%, %key%, %value%
    Return, %OUTPUT%
  }

  IniSaver(input, key, value) {
    Global SETTINGS
    IniWrite, %input%, %SETTINGS%, %key%, %value%
    Return, %OUTPUT%
  }

  ; --> Read in Settings from INI

    HK1 := IniReader("Hotkeys", "hk1")
    HK2 := IniReader("Hotkeys", "hk2")
    HK3 := IniReader("Hotkeys", "hk3")
    HK4 := IniReader("Hotkeys", "hk4")
    HK5 := IniReader("Hotkeys", "hk5")
    HK6 := IniReader("Hotkeys", "hk6")

    BM1 := IniReader("Bookmarks", "bm1")
    BM2 := IniReader("Bookmarks", "bm2")
    BM3 := IniReader("Bookmarks", "bm3")
    BM4 := IniReader("Bookmarks", "bm4")
    BM5 := IniReader("Bookmarks", "bm5")
    BM6 := IniReader("Bookmarks", "bm6")

    APP1 := IniReader("Apps", "app1")
    APP2 := IniReader("Apps", "app2")
    APP3 := IniReader("Apps", "app3")
    APP4 := IniReader("Apps", "app4")
    APP5 := IniReader("Apps", "app5")
    APP6 := IniReader("Apps", "app6")

    FOLDER1 := IniReader("Folders", "folder1")
    FOLDER2 := IniReader("Folders", "folder2")
    FOLDER3 := IniReader("Folders", "folder3")
    FOLDER4 := IniReader("Folders", "folder4")
    FOLDER5 := IniReader("Folders", "folder5")
    FOLDER6 := IniReader("Folders", "folder6")

  ; --|

;--|

; --> GUI

  ; Generated by AutoGUI 2.2.5a
  #NoEnv
  #SingleInstance Force
  SetWorkingDir %A_ScriptDir%

  Gui Add, StatusBar,, Status Bar
  Gui Add, Tab3, x416 y256 w0 h0, Tab 1|Tab 2
  Gui Add, Tab3, x8 y8 w536 h350, Hotkeys|BookMarks|Apps|Folders
  Gui Tab, 1, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w32 h21 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditHK1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditHK2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditHK3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditHK4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditHK5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditHK6
  Gui Add, Button, x32 y250 h30 w100 gsaveHotkeys, Save Hotkeys

  Gui Tab, 2, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w32 h21 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditBM1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditBM2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditBM3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditBM4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditBM5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditBM6
  Gui Add, Button, x32 y250 h30 w100 gsaveBookmarks, Save Bookmarks

  Gui Tab, 3, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditAPP1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditAPP2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditAPP3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditAPP4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditAPP5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditAPP6
  Gui Add, Button, x32 y250 h30 w100 gsaveApps, Save Apps

  Gui Tab, 4, 2
  Gui Add, Text, x32 y48 w33 h23 +0x200 Center, 1
  Gui Add, Text, x32 y80 w33 h23 +0x200 Center, 2
  Gui Add, Text, x32 y112 w33 h23 +0x200 Center, 3
  Gui Add, Text, x32 y144 w33 h23 +0x200 Center, 4
  Gui Add, Text, x32 y176 w33 h23 +0x200 Center, 5
  Gui Add, Text, x32 y208 w33 h23 +0x200 Center, 6
  Gui Add, Edit, x72 y48 w411 h24 vmyEditFOLDER1
  Gui Add, Edit, x72 y80 w411 h24 vmyEditFOLDER2
  Gui Add, Edit, x72 y112 w411 h24 vmyEditFOLDER3
  Gui Add, Edit, x72 y144 w411 h24 vmyEditFOLDER4
  Gui Add, Edit, x72 y176 w411 h24 vmyEditFOLDER5
  Gui Add, Edit, x72 y208 w411 h24 vmyEditFOLDER6
  Gui Add, Button, x32 y250 h30 w100 gsaveFolders, Save Folders

  GuiControl,, myEditHK1, %HK1%
  GuiControl,, myEditHK2, %HK2%
  GuiControl,, myEditHK3, %HK3%
  GuiControl,, myEditHK4, %HK4%
  GuiControl,, myEditHK5, %HK5%
  GuiControl,, myEditHK6, %HK6%

  GuiControl,, myEditBM1, %BM1%
  GuiControl,, myEditBM2, %BM2%
  GuiControl,, myEditBM3, %BM3%
  GuiControl,, myEditBM4, %BM4%
  GuiControl,, myEditBM5, %BM5%
  GuiControl,, myEditBM6, %BM6%

  GuiControl,, myEditAPP1, %APP1%
  GuiControl,, myEditAPP2, %APP2%
  GuiControl,, myEditAPP3, %APP3%
  GuiControl,, myEditAPP4, %APP4%
  GuiControl,, myEditAPP5, %APP5%
  GuiControl,, myEditAPP6, %APP6%

  GuiControl,, myEditFOLDER1, %FOLDER1%
  GuiControl,, myEditFOLDER2, %FOLDER2%
  GuiControl,, myEditFOLDER3, %FOLDER3%
  GuiControl,, myEditFOLDER4, %FOLDER4%
  GuiControl,, myEditFOLDER5, %FOLDER5%
  GuiControl,, myEditFOLDER6, %FOLDER6%


  Gui Show, w550 h400, Window
  Return

  GuiEscape:
  GuiClose:
      ExitApp

; --|

; --> Sub Routines
  saveHotkeys:
    guiControlGet, hk1Var,, myEditHK1
    guiControlGet, hk2Var,, myEditHK2
    guiControlGet, hk3Var,, myEditHK3
    guiControlGet, hk4Var,, myEditHK4
    guiControlGet, hk5Var,, myEditHK5
    guiControlGet, hk6Var,, myEditHK6
    IniSaver(hk1Var, "Hotkeys", "hk1")
    IniSaver(hk2Var, "Hotkeys", "hk2")
    IniSaver(hk3Var, "Hotkeys", "hk3")
    IniSaver(hk4Var, "Hotkeys", "hk4")
    IniSaver(hk5Var, "Hotkeys", "hk5")
    IniSaver(hk6Var, "Hotkeys", "hk6")

    MsgBox % "Hotkeys Saved!"

  Return

  saveBookmarks:
    guiControlGet, bm1Var,, myEditBM1
    guiControlGet, bm2Var,, myEditBM2
    guiControlGet, bm3Var,, myEditBM3
    guiControlGet, bm4Var,, myEditBM4
    guiControlGet, bm5Var,, myEditBM5
    guiControlGet, bm6Var,, myEditBM6
    IniSaver(bm1Var, "Bookmarks", "bm1")
    IniSaver(bm2Var, "Bookmarks", "bm2")
    IniSaver(bm3Var, "Bookmarks", "bm3")
    IniSaver(bm4Var, "Bookmarks", "bm4")
    IniSaver(bm5Var, "Bookmarks", "bm5")
    IniSaver(bm6Var, "Bookmarks", "bm6")

    MsgBox % "Bookmarks Saved!"
  Return

  saveApps:
    guiControlGet, app1Var,, myEditAPP1
    guiControlGet, app2Var,, myEditAPP2
    guiControlGet, app3Var,, myEditAPP3
    guiControlGet, app4Var,, myEditAPP4
    guiControlGet, app5Var,, myEditAPP5
    guiControlGet, app6Var,, myEditAPP6
    IniSaver(app1Var, "Apps", "app1")
    IniSaver(app2Var, "Apps", "app2")
    IniSaver(app3Var, "Apps", "app3")
    IniSaver(app4Var, "Apps", "app4")
    IniSaver(app5Var, "Apps", "app5")
    IniSaver(app6Var, "Apps", "app6")

    MsgBox % "Apps Saved!"

  Return

  saveFolders:
    guiControlGet, folder1Var,, myEditFOLDER1
    guiControlGet, folder2Var,, myEditFOLDER2
    guiControlGet, folder3Var,, myEditFOLDER3
    guiControlGet, folder4Var,, myEditFOLDER4
    guiControlGet, folder5Var,, myEditFOLDER5
    guiControlGet, folder6Var,, myEditFOLDER6
    IniSaver(folder1Var, "Folders", "folder1")
    IniSaver(folder2Var, "Folders", "folder2")
    IniSaver(folder3Var, "Folders", "folder3")
    IniSaver(folder4Var, "Folders", "folder4")
    IniSaver(folder5Var, "Folders", "folder5")
    IniSaver(folder6Var, "Folders", "folder6")

    MsgBox % "Folders Saved!"

  Return

;--|

